# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmvnorm_ <- function(nsamples, mean, covariance) {
    .Call('PET_rmvnorm_', PACKAGE = 'PET', nsamples, mean, covariance)
}

rmvnorm_cholesky_ <- function(nsamples, mean, cholesky) {
    .Call('PET_rmvnorm_cholesky_', PACKAGE = 'PET', nsamples, mean, cholesky)
}

dmvnorm_ <- function(x, mean, covariance) {
    .Call('PET_dmvnorm_', PACKAGE = 'PET', x, mean, covariance)
}

dmvnorm_cholesky_inverse_ <- function(x, mean, cholesky_inverse) {
    .Call('PET_dmvnorm_cholesky_inverse_', PACKAGE = 'PET', x, mean, cholesky_inverse)
}

